BeekeepersConference/Models/Beekeeper.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BeekeepersConference.Models;

public class Beekeeper
{
    [Required(ErrorMessage = "Анонимным участникам у нас не рады")]
    [DisplayName("Имя, фамилия")]
    public string Name { get; set; } = String.Empty;
    
    [Required(ErrorMessage = "Нам важно знать, откуда вы")]
    [DisplayName("Город")]
    public string City { get; set; } = String.Empty;
    
    [Required(ErrorMessage = "Поле обязательно для заполнения")]
    [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage="Это не email")]
    [DisplayName("Email")]
    public string Email { get; set; } = String.Empty;
    
    [Required(ErrorMessage = "Поле обязательно для заполнения")]
    [RegularExpression(@"^\+?(\d[\d-. ]+)?(\([\d-. ]+\))?[\d-. ]+\d$", ErrorMessage="Это не номер телефона")]
    [DisplayName("Номер телефона")]
    public string Phone { get; set; } = String.Empty;
    
    [DisplayName("Придёте с пчёлами?")]
    public bool Expected { get; set; }
}

BeekeepersConference/Models/ErrorViewModel.cs
namespace BeekeepersConference.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

BeekeepersConference/Models/Speaker.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BeekeepersConference.Models;

public class Speaker
{
    [Required(ErrorMessage = "Анонимным участникам у нас не рады")]
    [DisplayName("Имя, фамилия")]
    public string Name { get; set; } = string.Empty;
    
    [Required(ErrorMessage = "Нам важно знать, откуда вы")]
    [DisplayName("Город")]
    public string City { get; set; } = string.Empty;
    
    [Required(ErrorMessage = "Поле обязательно для заполнения")]
    [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage="Это не email")]
    [DisplayName("Email")]
    public string Email { get; set; } = string.Empty;
    
    [Required(ErrorMessage = "Поле обязательно для заполнения")]
    [RegularExpression(@"^\+?(\d[\d-. ]+)?(\([\d-. ]+\))?[\d-. ]+\d$", ErrorMessage="Это не номер телефона")]
    [DisplayName("Номер телефона")]
    public string Phone { get; set; } = string.Empty;

    [Required(ErrorMessage = "Поле обязательно для заполнения")]
    [DisplayName("Опыт пчеловодства в годах")]
    public int Experience { get; set; } 
}

BeekeepersConference/Controllers/BeekeeperRequestFormController.cs
using BeekeepersConference.Models;
using Microsoft.AspNetCore.Mvc;

namespace BeekeepersConference.Controllers;

public class BeekeeperRequestFormController : Controller
{
    // GET
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Index(Beekeeper beekeeper)
    {
        return ModelState.IsValid ? View("Accepted", beekeeper) : View();
    }
}

BeekeepersConference/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BeekeepersConference.Models;

namespace BeekeepersConference.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        int hour = DateTime.Now.Hour;
        const string user = "дорогой пчеловод";
        ViewBag.Hello = hour switch
        {
            < 6 => $"Доброй ночи, {user} :)",
            < 12 => $"Доброе утро, {user} :)",
            >= 18 => $"Добрый вечер, {user} :)",
            _ => $"Добрый день, {user} :)"
        };
        return View();
    }
    

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

BeekeepersConference/Controllers/SpeakerRequestFormController.cs
using BeekeepersConference.Models;
using Microsoft.AspNetCore.Mvc;

namespace BeekeepersConference.Controllers;

public class SpeakerRequestFormController : Controller
{
    // GET
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Index(Speaker speaker)
    {
        return ModelState.IsValid ? View("Accepted", speaker) : View();
    }
}

BeekeepersConference/Views/BeekeeperRequestForm/Accepted.cshtml
@model Beekeeper

@{
    ViewData["Title"] = "Заявка принята";
}

<div>
    <h1>@Model.Name, ваша заявка принята.</h1>
    <p>Накануне мы с вами дополнительно свяжемся.</p>
    @if (Model.Expected) {
        @:Для ваших пчёл будет выделен дополнительный улей. 
    }
    else { 
        @:На нашей конференции вы сможете приобрести отборных туркменских пчёл.
    }
</div>

BeekeepersConference/Views/BeekeeperRequestForm/Index.cshtml
@model Beekeeper

@{
    ViewData["Title"] = "Заявка участника";
}

<h4>Заявка участника</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" value="" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control"  value="" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Expected" class="control-label"></label>
                @Html.DropDownListFor(x => x.Expected, new[]
                {
                    new SelectListItem() { Text = "Да, возьму своих пчёл", Value = Boolean.TrueString},
                    new SelectListItem() { Text = "Нет, буду без пчёл", Value = Boolean.FalseString}
                })
                <span asp-validation-for="Expected" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="submit" value="Create" class="btn btn-primary btn-block m-lg-1" id="create"/>
                </div>
                <div  class="form-group col-md-6">
                    <a asp-controller="Home" asp-action="Index"  class="btn btn-secondary btn-block m-lg-1">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeekeepersConference/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Пчеловоды России";
}

<div class="text-center">
    <h1 class="display-4">@ViewBag.Hello</h1>
    <div>
        <p>30 февраля у нас проходит конференция с приглашёнными гостями из Туркменистана.</p>
        <p>Если ты хочешь принять в ней участие, заполни форму:</p>
        <div class="btn btn-outline-success">
            <a class="app-btn" asp-area="" asp-controller="BeekeeperRequestForm" asp-action="Index">Заявка участника</a>
            
        </div>
        <div class="btn btn-outline-success">
            <a class="app-btn" asp-area="" asp-controller="SpeakerRequestForm" asp-action="Index">Заявка спикера</a>
        </div>
    </div>
</div>

BeekeepersConference/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BeekeepersConference</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/BeekeepersConference.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeekeepersConference</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Beekeepers Conference
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BeekeepersConference/Views/SpeakerRequestForm/Accepted.cshtml
@model Speaker

@{
    ViewData["Title"] = "Заявка принята";
}

    <div>
        <h1>@Model.Name, ваша заявка принята.</h1>
        <p>Накануне мы с вами дополнительно свяжемся.</p>
        @if (Model.Experience > 5) {
            @:Пчеловоды России с нетерпением ждут ваших бесценных советов.
        }
    </div>

BeekeepersConference/Views/SpeakerRequestForm/Index.cshtml
@model Speaker

@{
    ViewData["Title"] = "Заявка спикера";
}

<h4>Заявка спикера</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control"  value="" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>              
            <div class="form-group">
                <label asp-for="Experience" class="control-label"></label>
                <input asp-for="Experience" class="form-control" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="submit" value="Create" class="btn btn-primary btn-block m-lg-1" id="create"/>
                </div>
                <div  class="form-group col-md-6">
                    <a asp-controller="Home" asp-action="Index"  class="btn btn-secondary btn-block m-lg-1">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}